name: Spring Boot CI/CD to Ubuntu EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: SCP JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "${{ secrets.TARGET_DIR }}/build/libs"

      - name: SSH and run on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/build/libs/logs
            pkill -f 'java -jar' || echo "No running server"
            export EC2_MYSQL=${{ secrets.EC2_MYSQL }}
            export EC2_PASSWORD=${{ secrets.EC2_PASSWORD }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export OPEN_API_KEY=${{ secrets.OPEN_API_KEY }}
            nohup java -jar /home/ubuntu/build/libs/collaboration.project-0.0.1-SNAPSHOT.jar > /home/ubuntu/build/libs/logs/app.log 2>&1 &
